Exercise 12
Tasnima123/DevOps-Course-Starter pull request #12
Opened 2021-11-06 18:57 UTC by Tasnima123

2021-11-10 17:29 UTC, hugh-emerson requested changes
Looks good except you've leaked various credentials.

Take a look at my other comments for details. When credentials are exposed like this, you should treat them as compromised and rotate the relevant passwords etc.

2021-11-10 17:29 UTC, hugh-emerson commented on outputs.tf
> +    }
This contains a password. So you should set sensitive = true to avoid it being printed out in the CD pipeline's logs

2021-11-10 17:29 UTC, hugh-emerson commented on .gitignore
> +.terraform.lock.hcl
You shouldn't actually ignore lock files. Like poetry.lock.

2021-11-10 17:29 UTC, hugh-emerson commented on .env.test
> +MONGODB_CONNECTION_STRING=mongodb://test:KlyeqKmSSaxR9t9ydKW9FFRmU4G5GkFu0pmahM2d2gpNS243or3RkndLIXR3cDeIPFk1xoi7C5AQ3Qka9U3Ynw==@test.mongo.cosmos.azure.com:10255/DefaultDatabase?ssl=true&replicaSet
You should make this more obviously fake. The password looks real.

2021-11-10 17:29 UTC, hugh-emerson commented on .travis.yml
> +- docker run -e FLASK_APP=todo_app/app -e FLASK_ENV=development -e SECRET_KEY=secret_key -e FLASK_SKIP_DOTENV=True -e MONGO_COLLECTION=todos -e WEBHOOK_URL -e client_id -e client_secret -e disable_lo
You should set the MONGODB_CONNECTION_STRING via a secure environment variable in Travis, not include it like this in the yaml file. Everyone in the world now has access to your database.

2021-11-10 17:29 UTC, hugh-emerson commented on .travis.yml
> +- docker run -e FLASK_APP=todo_app/app -e FLASK_ENV=development -e SECRET_KEY=secret_key -e FLASK_SKIP_DOTENV=True -e MONGO_COLLECTION=todos -e WEBHOOK_URL -e client_id -e client_secret -e disable_lo
Why does your app need a WEBHOOK_URL?

2021-11-10 17:29 UTC, hugh-emerson commented on webhook.sh
> +curl -dH -X POST "$cd_webhook"
cd_webhook is not an environment variable. It's an output variable from terraform. You can access it in the middle of a bash command with `$(terraform output -raw cd_webhook)`

Once that works, you can delete the previous curl command (along with deleting any manually created resources that still exist. Everything should now be managed via Terraform)

2021-11-10 17:29 UTC, hugh-emerson commented on variables.tf
> +    default="150fb9c8e93fc2ea35fc1b0431336802af8454ba"
This looks like a real value. But secrets should not be committed to source code, even if this repository were private.

Don't have a default value. You are already passing in the value in your terraform apply command.

2021-11-10 17:29 UTC, hugh-emerson commented on  main.tf
> +        "SECRET_KEY"="secret-key"
Not important for this practice exercise, but for a real app the secret key should be treated like a secret, as the name implies. It's used to encrypt cookies and if it is leaked then anyone could pretend to be logged into your application as anyone else.

2021-11-17 12:58 UTC, JackMead approved these changes
Thanks for making those changes, I can't see any credentials still leaked here so happy for you to merge this when you're ready

2021-11-17 13:06 UTC, merged